apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: pg-ha-dolores
spec:
  imageName: quay.io/enterprisedb/postgresql:13.3-1
  instances: 3

  storage:
    size: 1Gi

  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised
  postgresql: 
    parameters: 
      wal_keep_size: 768MB

  #postgresql:
  #  parameters:
  #  pg_hba:
  #      - local all all md5

  bootstrap:
    initdb:
      options: ['-E','UTF8']
      database: shogunworld
      owner: maeve
      secret:
        name: pg-ha-shogunworld-maeve
  monitoring:
    customQueriesConfigMap:
      - name: example-monitoring
        key: custom-queries
